version: '2.3'
services:
  experiment:
    ports:
    - 8888:8888
    runtime: nvidia
    volumes:
    - ..:/app
    build:
      context: .
      dockerfile: gpu.Dockerfile
    image: tanimu/partialconv
